import type { Metadata } from "next";
import { Inter, Geist, Noto_Sans_Georgian } from "next/font/google";
import "./globals.css";
import Navbar from "./UI/nav";
import FooterSection from "./UI/footer";
import { cn } from "@/lib/utils";
const geist = Geist({subsets:['latin'],variable:'--font-sans'});


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const georgian = Noto_Sans_Georgian({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-georgian',
});

export const metadata: Metadata = {
  title: "eezyhealth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${inter.variable} ${georgian.variable} antialiased w-screen h-screen`}
      >
        <Navbar/>
        <main className="w-full mt-12 flex flex-col items-center justify-center grow">
          {children}
        </main>
        
        <FooterSection/>
      </body>
    </html>
  );
}
